<?php

namespace Database\Seeders;

use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ActivitySeeder extends Seeder
{
    public function run(): void
    {
        $activities = [
            [
                'name' => 'Bungee Jumping at The Last Resort',
                'description' => 'Experience the ultimate adrenaline rush with Nepal\'s first and most famous bungee jumping site. Plunge 160 meters into the tropical gorge of the Bhote Koshi River.',
                'type' => 'bungee',
                'location' => 'The Last Resort, Kodari Highway',
                'city' => 'Sindhupalchok',
                'duration' => '1 hour',
                'price' => 120.00,
                'max_participants' => 20,
                'difficulty_level' => 'extreme',
                'includes' => ['Bungee jump', 'Safety equipment', 'Professional guides', 'Certificate', 'Transportation from resort'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Minimum age: 16 years. Weight: 40-100 kg. Not suitable for pregnant women or those with heart conditions.',
                'safety_info' => 'Operated by experienced international team. Equipment meets international safety standards.',
            ],
            [
                'name' => 'Paragliding Over Phewa Lake',
                'description' => 'Soar like a bird over the beautiful Phewa Lake with the majestic Annapurna range as your backdrop. A truly magical experience in Pokhara.',
                'type' => 'paragliding',
                'location' => 'Sarangkot, Pokhara',
                'city' => 'Pokhara',
                'duration' => '30 minutes',
                'price' => 95.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Tandem flight', 'Professional pilot', 'Photos and videos', 'Safety equipment', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'No experience required. Wear comfortable clothing and closed shoes.',
                'safety_info' => 'All pilots are APPI certified. Weather dependent activity.',
            ],
            [
                'name' => 'Trishuli River Rafting',
                'description' => 'Navigate the exciting rapids of the Trishuli River. Perfect for beginners and experienced rafters alike with beautiful scenery along the way.',
                'type' => 'rafting',
                'location' => 'Trishuli River, Charaundi',
                'city' => 'Dhading',
                'duration' => '4 hours',
                'price' => 45.00,
                'max_participants' => 30,
                'difficulty_level' => 'moderate',
                'includes' => ['Rafting equipment', 'Professional guides', 'Lunch', 'Safety briefing', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Minimum age: 12 years with parental consent.',
                'safety_info' => 'IRF certified guides. All safety equipment provided.',
            ],
            [
                'name' => 'Everest Base Camp Trek',
                'description' => 'The ultimate trekking adventure to the base of the world\'s highest peak. 12 days of breathtaking mountain views and Sherpa culture.',
                'type' => 'trekking',
                'location' => 'Sagarmatha National Park',
                'city' => 'Solukhumbu',
                'duration' => '12 days',
                'price' => 1250.00,
                'max_participants' => 12,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Permits', 'Flight Kathmandu-Lukla', 'First aid'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Good physical fitness required. Previous trekking experience recommended. Medical clearance advised.',
                'safety_info' => 'Experienced guides trained in altitude sickness management. Emergency evacuation plan in place.',
            ],
            [
                'name' => 'Zip Flying Pokhara',
                'description' => 'Experience the world\'s longest, steepest, and fastest zip line. An incredible 1.8 km ride with stunning mountain views.',
                'type' => 'zipline',
                'location' => 'Sarangkot, Pokhara',
                'city' => 'Pokhara',
                'duration' => '2 minutes',
                'price' => 85.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Zipline ride', 'Safety equipment', 'Professional guides', 'Transportation', 'Certificate'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Weight: 35-125 kg. No age restriction but minors need parental consent.',
                'safety_info' => 'Uses European standard equipment. Regular safety inspections.',
            ],
            [
                'name' => 'Skydiving Over Everest',
                'description' => 'The ultimate bucket list experience - skydiving with Mount Everest in the background. Tandem jump from 25,000 feet.',
                'type' => 'skydiving',
                'location' => 'Syangboche, Everest Region',
                'city' => 'Solukhumbu',
                'duration' => '1 hour',
                'price' => 2500.00,
                'max_participants' => 4,
                'difficulty_level' => 'extreme',
                'includes' => ['Tandem skydive', 'Professional instructor', 'Full gear', 'Photos and video', 'Helicopter transport', 'Certificate'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be physically fit. No prior experience required. Weight limit: 95 kg.',
                'safety_info' => 'World-class instructors with thousands of jumps. Premium safety equipment.',
            ],
            [
                'name' => 'Canyoning at Jalbire',
                'description' => 'Explore hidden canyons with waterfalls, slides, and jumps. A refreshing adventure in Nepal\'s tropical landscape.',
                'type' => 'canyoning',
                'location' => 'Jalbire Waterfall, Aanboo Khaireni',
                'city' => 'Chitwan',
                'duration' => '5 hours',
                'price' => 75.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['All equipment', 'Professional guides', 'Lunch', 'Transportation', 'Safety briefing'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Minimum age: 14 years.',
                'safety_info' => 'International standard equipment. Guides are canyoning certified.',
            ],
            [
                'name' => 'Rock Climbing at Nagarjun',
                'description' => 'Challenge yourself on the limestone cliffs of Nagarjun Forest. Routes available for all skill levels from beginner to advanced.',
                'type' => 'rock_climbing',
                'location' => 'Nagarjun Forest Reserve',
                'city' => 'Kathmandu',
                'duration' => '4 hours',
                'price' => 55.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Climbing equipment', 'Professional instructor', 'Safety gear', 'Snacks', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness level required. All skill levels welcome.',
                'safety_info' => 'Certified climbing instructors. All safety equipment regularly inspected.',
            ],
            [
                'name' => 'Annapurna Base Camp Trek',
                'description' => 'Trek to the base of the 10th highest mountain in the world. Experience diverse landscapes from subtropical forests to alpine zones.',
                'type' => 'trekking',
                'location' => 'Annapurna Conservation Area',
                'city' => 'Kaski',
                'duration' => '7-10 days',
                'price' => 850.00,
                'max_participants' => 12,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Permits', 'Transportation', 'First aid'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Good physical fitness required. Some trekking experience recommended.',
                'safety_info' => 'Experienced guides with altitude sickness training. Helicopter evacuation available.',
            ],
            [
                'name' => 'Langtang Valley Trek',
                'description' => 'Beautiful trek through the Langtang Valley, known as the valley of glaciers. Rich Tamang culture and stunning mountain views.',
                'type' => 'trekking',
                'location' => 'Langtang National Park',
                'city' => 'Rasuwa',
                'duration' => '7-8 days',
                'price' => 650.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Permits', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Moderate fitness level required. No previous experience needed.',
                'safety_info' => 'Experienced local guides. Weather dependent activity.',
            ],
            [
                'name' => 'Gosaikunda Lake Trek',
                'description' => 'Trek to the sacred alpine lakes at 4,380m. Holy pilgrimage site for Hindus and Buddhists.',
                'type' => 'trekking',
                'location' => 'Langtang National Park',
                'city' => 'Rasuwa',
                'duration' => '5-6 days',
                'price' => 550.00,
                'max_participants' => 12,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'All meals', 'Accommodation', 'Permits', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Good fitness level required. High altitude trekking experience helpful.',
                'safety_info' => 'Proper acclimatization essential. Altitude sickness awareness required.',
            ],
            [
                'name' => 'Makalu Base Camp Trek',
                'description' => 'Remote trek to the base of the world fifth highest peak. Untouched wilderness and diverse ecosystems.',
                'type' => 'trekking',
                'location' => 'Makalu Barun National Park',
                'city' => 'Sankhuwasabha',
                'duration' => '16-18 days',
                'price' => 1800.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Camping equipment', 'Permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Excellent physical fitness required. Previous high-altitude trekking experience essential.',
                'safety_info' => 'Very remote area. Experienced guides with wilderness first aid. Satellite communication available.',
            ],
            [
                'name' => 'Kanchenjunga Base Camp Trek',
                'description' => 'Trek to the base of the world third highest mountain. Restricted area requiring special permits.',
                'type' => 'trekking',
                'location' => 'Kanchenjunga Conservation Area',
                'city' => 'Taplejung',
                'duration' => '18-20 days',
                'price' => 2200.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Camping equipment', 'Special permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Excellent fitness required. Previous trekking experience mandatory. Special permits needed.',
                'safety_info' => 'Restricted area trek. Mandatory guide requirement. Remote location with limited facilities.',
            ],
            [
                'name' => 'Manaslu Circuit Trek',
                'description' => 'Circuit trek around the eighth highest mountain. Dramatic landscapes and authentic Tibetan culture.',
                'type' => 'trekking',
                'location' => 'Manaslu Conservation Area',
                'city' => 'Gorkha',
                'duration' => '14-16 days',
                'price' => 1200.00,
                'max_participants' => 10,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Special permits', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Good fitness level required. Previous trekking experience recommended.',
                'safety_info' => 'Restricted area requiring special permits. Mandatory guide. Proper acclimatization schedule.',
            ],
            [
                'name' => 'Upper Mustang Trek',
                'description' => 'Explore the mystical Forbidden Kingdom of Mustang. Ancient Tibetan Buddhist culture in a high desert landscape.',
                'type' => 'trekking',
                'location' => 'Upper Mustang',
                'city' => 'Lo Manthang',
                'duration' => '10-12 days',
                'price' => 1500.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Special permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Special permit required. Minimum group size regulations apply.',
                'safety_info' => 'Restricted area. Mandatory guide. High altitude desert environment.',
            ],
            [
                'name' => 'Dolpo Trek',
                'description' => 'Remote trek to one of Nepal most isolated regions. Bon culture, Shey Gompa, and pristine wilderness.',
                'type' => 'trekking',
                'location' => 'Dolpo',
                'city' => 'Dunai',
                'duration' => '15-18 days',
                'price' => 1900.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Camping equipment', 'Special permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Excellent fitness required. Special permits mandatory. Previous trekking experience essential.',
                'safety_info' => 'Very remote area. Restricted permits required. Limited facilities.',
            ],
            [
                'name' => 'Rara Lake Trek',
                'description' => 'Trek to Nepal largest lake in the remote Mugu district. Pristine alpine wilderness and unique culture.',
                'type' => 'trekking',
                'location' => 'Rara National Park',
                'city' => 'Mugu',
                'duration' => '8-10 days',
                'price' => 950.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Professional guide', 'Porter service', 'All meals', 'Accommodation', 'Permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Good fitness level required. Accessible by flight or trek.',
                'safety_info' => 'Remote location. Flight access recommended. Experienced guides provided.',
            ],
            [
                'name' => 'Helambu Trek',
                'description' => 'Short trek near Kathmandu through Sherpa villages. Perfect for those with limited time.',
                'type' => 'trekking',
                'location' => 'Helambu',
                'city' => 'Sindhupalchok',
                'duration' => '5-6 days',
                'price' => 450.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Professional guide', 'All meals', 'Accommodation', 'Permits', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for beginners. No previous experience required.',
                'safety_info' => 'Easy access from Kathmandu. Low altitude trek.',
            ],
            [
                'name' => 'Panchase Trek',
                'description' => 'Short eco-trek from Pokhara with stunning Annapurna views. Excellent for families and beginners.',
                'type' => 'trekking',
                'location' => 'Panchase',
                'city' => 'Kaski',
                'duration' => '3-4 days',
                'price' => 350.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Professional guide', 'All meals', 'Accommodation', 'Permits', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all fitness levels. Family-friendly.',
                'safety_info' => 'Easy access from Pokhara. Low altitude. Safe for children.',
            ],
            [
                'name' => 'Chitwan Jungle Safari',
                'description' => 'Experience Nepals most famous wildlife destination. Spot rhinos, tigers, elephants, and over 500 bird species.',
                'type' => 'safari',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '2-3 days',
                'price' => 250.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Jeep safari', 'Canoe ride', 'Elephant activities', 'Nature walks', 'Cultural dance', 'All meals', 'Accommodation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. No special fitness required.',
                'safety_info' => 'Experienced naturalist guides. Follow all safety guidelines in the park.',
            ],
            [
                'name' => 'Bardia National Park Safari',
                'description' => 'Wildlife safari in Nepal largest national park. Higher chance of spotting Bengal tigers than anywhere else.',
                'type' => 'safari',
                'location' => 'Bardia National Park',
                'city' => 'Bardiya',
                'duration' => '3-4 days',
                'price' => 350.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Jeep safari', 'Elephant safari', 'Jungle walks', 'Rafting', 'Cultural programs', 'All meals', 'Accommodation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Some activities require basic fitness.',
                'safety_info' => 'Expert wildlife guides. Follow all safety protocols.',
            ],
            [
                'name' => 'Koshi Tappu Bird Watching',
                'description' => 'Premier bird watching destination with over 400 species. Perfect for ornithology enthusiasts.',
                'type' => 'bird_watching',
                'location' => 'Koshi Tappu Wildlife Reserve',
                'city' => 'Saptari',
                'duration' => '2-3 days',
                'price' => 200.00,
                'max_participants' => 12,
                'difficulty_level' => 'easy',
                'includes' => ['Expert bird guide', 'Boat safari', 'Nature walks', 'All meals', 'Accommodation', 'Equipment'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'No experience needed. Patience and keen observation helpful.',
                'safety_info' => 'Expert ornithologist guides provided. Safe environment.',
            ],
            [
                'name' => 'Suklaphanta Wildlife Safari',
                'description' => 'Explore Nepal largest grassland habitat with the largest herd of swamp deer in the world.',
                'type' => 'safari',
                'location' => 'Suklaphanta Wildlife Reserve',
                'city' => 'Kanchanpur',
                'duration' => '2-3 days',
                'price' => 280.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Jeep safari', 'Nature walks', 'Bird watching', 'Tharu culture', 'All meals', 'Accommodation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Experienced guides. Safe safari environment.',
            ],
            [
                'name' => 'Parsa Wildlife Reserve Safari',
                'description' => 'Lesser-known wildlife reserve with excellent tiger and elephant spotting opportunities.',
                'type' => 'safari',
                'location' => 'Parsa National Park',
                'city' => 'Parsa',
                'duration' => '2-3 days',
                'price' => 220.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Jeep safari', 'Jungle walks', 'Elephant activities', 'Tharu culture', 'All meals', 'Accommodation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Expert guides. Safe wildlife viewing.',
            ],
            [
                'name' => 'Banke National Park Safari',
                'description' => 'Tiger conservation area with excellent wildlife viewing opportunities.',
                'type' => 'safari',
                'location' => 'Banke National Park',
                'city' => 'Banke',
                'duration' => '2-3 days',
                'price' => 260.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Jeep safari', 'Jungle walks', 'Bird watching', 'Tharu culture', 'All meals', 'Accommodation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Experienced naturalist guides. Safe environment.',
            ],
            [
                'name' => 'Kali Gandaki River Rafting',
                'description' => 'Raft the worlds deepest gorge on the sacred Kali Gandaki River. Multi-day adventure with camping.',
                'type' => 'rafting',
                'location' => 'Kali Gandaki River',
                'city' => 'Myagdi',
                'duration' => '3 days',
                'price' => 350.00,
                'max_participants' => 20,
                'difficulty_level' => 'moderate',
                'includes' => ['Rafting equipment', 'Professional guides', 'All meals', 'Camping', 'Safety briefing', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Minimum age: 14 years.',
                'safety_info' => 'IRF certified guides. State-of-the-art safety equipment.',
            ],
            [
                'name' => 'Seti River Rafting',
                'description' => 'Scenic whitewater rafting on the beautiful Seti River. Perfect for families.',
                'type' => 'rafting',
                'location' => 'Seti River',
                'city' => 'Kaski',
                'duration' => '2 days',
                'price' => 180.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Rafting equipment', 'Professional guides', 'All meals', 'Camping', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'No experience needed. Minimum age: 8 years with parents.',
                'safety_info' => 'Family-friendly rapids. Professional guides with family experience.',
            ],
            [
                'name' => 'Bhote Koshi River Rafting',
                'description' => 'Extreme whitewater rafting near the Tibet border. Challenging rapids for adventure seekers.',
                'type' => 'rafting',
                'location' => 'Bhote Koshi River',
                'city' => 'Sindhupalchok',
                'duration' => '1 day',
                'price' => 85.00,
                'max_participants' => 20,
                'difficulty_level' => 'extreme',
                'includes' => ['Rafting equipment', 'Professional guides', 'Lunch', 'Safety briefing', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Previous rafting experience recommended. Minimum age: 16.',
                'safety_info' => 'Expert IRF certified guides. Safety kayakers. Rescue trained team.',
            ],
            [
                'name' => 'Marshyangdi River Rafting',
                'description' => 'Technical whitewater rafting through stunning Himalayan scenery. Challenging rapids for experienced rafters.',
                'type' => 'rafting',
                'location' => 'Marshyangdi River',
                'city' => 'Lamjung',
                'duration' => '2 days',
                'price' => 220.00,
                'max_participants' => 18,
                'difficulty_level' => 'challenging',
                'includes' => ['Rafting equipment', 'Professional guides', 'All meals', 'Camping', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Previous rafting experience recommended.',
                'safety_info' => 'Expert guides. High safety standards.',
            ],
            [
                'name' => 'Karnali River Expedition',
                'description' => 'Multi-day expedition on Nepals longest river. Remote wilderness and challenging rapids.',
                'type' => 'rafting',
                'location' => 'Karnali River',
                'city' => 'Humla',
                'duration' => '7 days',
                'price' => 850.00,
                'max_participants' => 15,
                'difficulty_level' => 'challenging',
                'includes' => ['Rafting equipment', 'Professional guides', 'All meals', 'Camping', 'Transportation from Nepalgunj'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Previous rafting experience essential.',
                'safety_info' => 'Highly experienced expedition guides. Satellite communication.',
            ],
            [
                'name' => 'Sun Koshi River Expedition',
                'description' => 'The ultimate rafting expedition - 270km through the heart of Nepal. One of the worlds top 10 river journeys.',
                'type' => 'rafting',
                'location' => 'Sun Koshi River',
                'city' => 'Dolakha',
                'duration' => '9 days',
                'price' => 950.00,
                'max_participants' => 20,
                'difficulty_level' => 'challenging',
                'includes' => ['Rafting equipment', 'Professional guides', 'All meals', 'Camping', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Must be able to swim. Previous rafting experience recommended.',
                'safety_info' => 'World-class expedition team. Comprehensive safety equipment.',
            ],
            [
                'name' => 'Mountain Flight Everest Experience',
                'description' => 'Scenic mountain flight from Kathmandu with guaranteed window seat to view Everest and the Himalayas.',
                'type' => 'mountain_flight',
                'location' => 'Kathmandu Airport',
                'city' => 'Kathmandu',
                'duration' => '1 hour',
                'price' => 250.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Guaranteed window seat', 'Airport transfer', 'Breakfast', 'Flight certificate'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Not recommended for very young children.',
                'safety_info' => 'Experienced mountain pilots. Modern aircraft. Weather dependent.',
            ],
            [
                'name' => 'Ultralight Flight Pokhara',
                'description' => 'Open cockpit flying experience over Pokhara with Annapurna range views. Thrilling and scenic.',
                'type' => 'ultralight',
                'location' => 'Pokhara Airport',
                'city' => 'Pokhara',
                'duration' => '30-60 minutes',
                'price' => 180.00,
                'max_participants' => 2,
                'difficulty_level' => 'moderate',
                'includes' => ['Ultralight flight', 'Experienced pilot', 'Safety briefing', 'Video footage'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Weight limit: 100kg. Not for those with fear of heights.',
                'safety_info' => 'Licensed ultralight pilots. Daily safety inspections.',
            ],
            [
                'name' => 'Helicopter Tour to Everest Base Camp',
                'description' => 'Luxury helicopter tour to Everest Base Camp with breakfast at the highest hotel in the world.',
                'type' => 'helicopter',
                'location' => 'Everest Region',
                'city' => 'Solukhumbu',
                'duration' => '4 hours',
                'price' => 1200.00,
                'max_participants' => 5,
                'difficulty_level' => 'easy',
                'includes' => ['Helicopter flight', 'Breakfast at Everest View Hotel', 'Landing at EBC', 'All permits'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Medical clearance required. Weight restrictions apply.',
                'safety_info' => 'Experienced high-altitude pilots. Oxygen available. Weather dependent.',
            ],
            [
                'name' => 'Mountain Biking in Kathmandu Valley',
                'description' => 'Explore the Kathmandu Valley on two wheels. Trails for all skill levels through villages and hills.',
                'type' => 'mountain_biking',
                'location' => 'Kathmandu Valley',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 75.00,
                'max_participants' => 12,
                'difficulty_level' => 'moderate',
                'includes' => ['Quality mountain bike', 'Helmet', 'Guide', 'Lunch', 'Support vehicle'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Basic cycling ability required. Moderate fitness level.',
                'safety_info' => 'Experienced cycling guides. First aid support.',
            ],
            [
                'name' => 'Mountain Biking Annapurna Circuit',
                'description' => 'Epic mountain biking journey on the worlds most famous trekking route.',
                'type' => 'mountain_biking',
                'location' => 'Annapurna Circuit',
                'city' => 'Kaski',
                'duration' => '10-12 days',
                'price' => 1200.00,
                'max_participants' => 10,
                'difficulty_level' => 'challenging',
                'includes' => ['Quality mountain bike', 'All equipment', 'Guide', 'Support vehicle', 'All meals', 'Accommodation', 'Permits'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Advanced mountain biking skills required. High altitude experience recommended.',
                'safety_info' => 'Expert mountain bike guides. Support vehicle always nearby.',
            ],
            [
                'name' => 'Kathmandu Heritage Walking Tour',
                'description' => 'Guided walk through Kathmandus UNESCO World Heritage Sites. Durbar Square, Swayambhu, and more.',
                'type' => 'cultural',
                'location' => 'Kathmandu Durbar Square',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 45.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Lunch', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Walking involved.',
                'safety_info' => 'Knowledgeable local guides. Safe route.',
            ],
            [
                'name' => 'Patan Durbar Square Tour',
                'description' => 'Explore the artistic heart of the Kathmandu Valley. Ancient temples and traditional crafts.',
                'type' => 'cultural',
                'location' => 'Patan Durbar Square',
                'city' => 'Patan',
                'duration' => 'Half day',
                'price' => 35.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Refreshments'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Experienced cultural guides. Safe environment.',
            ],
            [
                'name' => 'Bhaktapur Ancient City Tour',
                'description' => 'Step back in time in the best-preserved ancient city in the Kathmandu Valley. Pottery, art, and architecture.',
                'type' => 'cultural',
                'location' => 'Bhaktapur Durbar Square',
                'city' => 'Bhaktapur',
                'duration' => '1 day',
                'price' => 55.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Traditional lunch', 'Pottery demonstration'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Walking on uneven surfaces.',
                'safety_info' => 'Knowledgeable local guides. Pedestrian-friendly area.',
            ],
            [
                'name' => 'Nagarkot Sunrise View Tour',
                'description' => 'Early morning drive to Nagarkot for spectacular Himalayan sunrise views. Return via ancient Changu Narayan temple.',
                'type' => 'sightseeing',
                'location' => 'Nagarkot',
                'city' => 'Bhaktapur',
                'duration' => 'Half day',
                'price' => 40.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Breakfast', 'Guide', 'Entry fees'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Early morning start. Suitable for all ages.',
                'safety_info' => 'Experienced driver. Weather dependent for views.',
            ],
            [
                'name' => 'Lumbini Pilgrimage Tour',
                'description' => 'Visit the birthplace of Lord Buddha. Sacred gardens, ancient ruins, and international monasteries.',
                'type' => 'pilgrimage',
                'location' => 'Lumbini Development Zone',
                'city' => 'Lumbini',
                'duration' => '1-2 days',
                'price' => 120.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Transportation', 'Meditation session'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Respectful attire required.',
                'safety_info' => 'Peaceful environment. Knowledgeable guides.',
            ],
            [
                'name' => 'Janakpur Religious Tour',
                'description' => 'Visit the ancient kingdom of Mithila and the sacred Janaki Temple. Experience Maithili culture.',
                'type' => 'pilgrimage',
                'location' => 'Janaki Temple',
                'city' => 'Janakpur',
                'duration' => '1 day',
                'price' => 80.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Transportation', 'Cultural performance'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Conservative dress recommended.',
                'safety_info' => 'Safe pilgrimage site. Experienced guides.',
            ],
            [
                'name' => 'Pashupatinath Temple Tour',
                'description' => 'Visit Nepals most sacred Hindu temple and cremation ghats. Spiritual and cultural experience.',
                'type' => 'pilgrimage',
                'location' => 'Pashupatinath Temple',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 35.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Evening aarti ceremony'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Non-Hindus cannot enter main temple. Respectful behavior required.',
                'safety_info' => 'Sacred site. Follow guide instructions.',
            ],
            [
                'name' => 'Boudhanath Stupa Circumambulation',
                'description' => 'Experience Tibetan Buddhism at the largest stupa in Nepal. Join the kora with pilgrims.',
                'type' => 'pilgrimage',
                'location' => 'Boudhanath Stupa',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 30.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Tea at rooftop cafe', 'Prayer flags'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Clockwise walking only.',
                'safety_info' => 'Peaceful environment. Wheelchair accessible.',
            ],
            [
                'name' => 'Swayambhunath Monkey Temple Tour',
                'description' => 'Climb the 365 steps to the ancient stupa overlooking Kathmandu. Meet the famous temple monkeys.',
                'type' => 'pilgrimage',
                'location' => 'Swayambhunath',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 25.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Expert guide', 'Entry fees', 'Refreshments'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => '365 steps to climb. Alternative road access available.',
                'safety_info' => 'Watch for monkeys. Secure belongings.',
            ],
            [
                'name' => 'Cooking Class in Kathmandu',
                'description' => 'Learn to cook authentic Nepali dishes including momos, dal bhat, and Newari specialties.',
                'type' => 'cooking',
                'location' => 'Traditional Kitchen',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 55.00,
                'max_participants' => 8,
                'difficulty_level' => 'easy',
                'includes' => ['All ingredients', 'Recipe book', 'Meal tasting', 'Certificate'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'No cooking experience required. Vegetarian options available.',
                'safety_info' => 'Clean kitchen. Food safety standards.',
            ],
            [
                'name' => 'Pottery Making in Bhaktapur',
                'description' => 'Try your hand at traditional pottery on the potters square. Create your own clay masterpiece.',
                'type' => 'workshop',
                'location' => 'Pottery Square',
                'city' => 'Bhaktapur',
                'duration' => '2 hours',
                'price' => 35.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Clay and tools', 'Expert instruction', 'One fired piece to take home'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Get ready to get messy!',
                'safety_info' => 'Safe environment. Experienced instructors.',
            ],
            [
                'name' => 'Thangka Painting Workshop',
                'description' => 'Learn the ancient art of Tibetan Buddhist painting from master artists.',
                'type' => 'workshop',
                'location' => 'Thangka Art School',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 85.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['Materials', 'Expert instruction', 'Your own thangka to keep'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Patience and attention to detail. No artistic experience required.',
                'safety_info' => 'Traditional art materials. Safe environment.',
            ],
            [
                'name' => 'Yoga and Meditation Retreat',
                'description' => 'Rejuvenate with daily yoga and meditation in the shadow of the Himalayas.',
                'type' => 'wellness',
                'location' => 'Retreat Center',
                'city' => 'Pokhara',
                'duration' => '3 days',
                'price' => 350.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Yoga classes', 'Meditation sessions', 'All meals', 'Accommodation', 'Nature walks'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all levels. Bring comfortable clothing.',
                'safety_info' => 'Certified yoga instructors. Safe environment.',
            ],
            [
                'name' => 'Ayurvedic Spa Treatment',
                'description' => 'Traditional Ayurvedic healing and massage therapies from experienced practitioners.',
                'type' => 'wellness',
                'location' => 'Ayurvedic Center',
                'city' => 'Kathmandu',
                'duration' => '2 hours',
                'price' => 120.00,
                'max_participants' => 4,
                'difficulty_level' => 'easy',
                'includes' => ['Consultation', 'Full body massage', 'Steam bath', 'Herbal tea'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Inform staff of any medical conditions.',
                'safety_info' => 'Certified Ayurvedic practitioners. Natural products.',
            ],
            [
                'name' => 'Ice Climbing in Langtang',
                'description' => 'Learn ice climbing on frozen waterfalls with professional instructors.',
                'type' => 'ice_climbing',
                'location' => 'Langtang Valley',
                'city' => 'Rasuwa',
                'duration' => '1 day',
                'price' => 150.00,
                'max_participants' => 6,
                'difficulty_level' => 'extreme',
                'includes' => ['All equipment', 'Professional instruction', 'Lunch', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'High fitness level required. Previous climbing experience helpful.',
                'safety_info' => 'UIAGM certified guides. All safety equipment provided.',
            ],
            [
                'name' => 'Peak Climbing - Island Peak',
                'description' => 'Climb Island Peak (6189m), one of the most popular trekking peaks in Nepal.',
                'type' => 'peak_climbing',
                'location' => 'Everest Region',
                'city' => 'Solukhumbu',
                'duration' => '15 days',
                'price' => 1800.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Climbing Sherpa', 'All equipment', 'All meals', 'Accommodation', 'Permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Excellent fitness required. High altitude trekking experience essential.',
                'safety_info' => 'Experienced climbing Sherpas. Proper acclimatization schedule.',
            ],
            [
                'name' => 'Peak Climbing - Mera Peak',
                'description' => 'Climb Mera Peak (6476m), the highest trekking peak in Nepal. Stunning Everest views from summit.',
                'type' => 'peak_climbing',
                'location' => 'Everest Region',
                'city' => 'Solukhumbu',
                'duration' => '18 days',
                'price' => 2200.00,
                'max_participants' => 8,
                'difficulty_level' => 'challenging',
                'includes' => ['Professional guide', 'Climbing Sherpa', 'All equipment', 'All meals', 'Accommodation', 'Permits', 'Flights'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Excellent fitness required. Technical climbing skills needed.',
                'safety_info' => 'Expert climbing team. Comprehensive safety equipment.',
            ],
            [
                'name' => 'Paragliding Cross Country',
                'description' => 'Extended cross-country paragliding flight from Pokhara to distant landing zones.',
                'type' => 'paragliding',
                'location' => 'Pokhara Valley',
                'city' => 'Pokhara',
                'duration' => '1-2 hours',
                'price' => 180.00,
                'max_participants' => 6,
                'difficulty_level' => 'moderate',
                'includes' => ['Tandem flight', 'APPI certified pilot', 'Extended flight time', 'Photos', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Must have done standard tandem flight before.',
                'safety_info' => 'Highly experienced pilots. Weather dependent.',
            ],
            [
                'name' => 'Canopy Tree Climbing',
                'description' => 'Climb into the canopy of giant trees in the Chitwan jungle using professional equipment.',
                'type' => 'adventure',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '3 hours',
                'price' => 65.00,
                'max_participants' => 8,
                'difficulty_level' => 'moderate',
                'includes' => ['All equipment', 'Professional instruction', 'Safety briefing'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness required. Not suitable for those with fear of heights.',
                'safety_info' => 'Professional climbing equipment. Trained instructors.',
            ],
            [
                'name' => 'Jungle Survival Course',
                'description' => 'Learn essential jungle survival skills including fire making, shelter building, and foraging.',
                'type' => 'adventure',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '2 days',
                'price' => 280.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Expert instructor', 'All equipment', 'Basic meals', 'Accommodation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Good fitness level. Willingness to rough it.',
                'safety_info' => 'Experienced survival instructors. Safety always priority.',
            ],
            [
                'name' => 'Elephant Bathing Experience',
                'description' => 'Get up close with elephants and help bathe them in the river. Unique wildlife interaction.',
                'type' => 'wildlife',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '1 hour',
                'price' => 35.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Elephant interaction', 'Bathing experience', 'Mahout guidance'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Bring change of clothes. Be prepared to get wet.',
                'safety_info' => 'Experienced mahouts always present. Follow instructions.',
            ],
            [
                'name' => 'Elephant Safari in Chitwan',
                'description' => 'Traditional elephant-back safari through the jungle grasslands to spot wildlife.',
                'type' => 'safari',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '2 hours',
                'price' => 45.00,
                'max_participants' => 4,
                'difficulty_level' => 'easy',
                'includes' => ['Elephant ride', 'Mahout guide', 'Park entry'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Not recommended for those with back problems.',
                'safety_info' => 'Experienced elephants and mahouts. Safety briefing provided.',
            ],
            [
                'name' => 'Jeep Safari in Bardia',
                'description' => '4x4 jeep safari deep into Bardia National Park for wildlife spotting including tigers.',
                'type' => 'safari',
                'location' => 'Bardia National Park',
                'city' => 'Bardiya',
                'duration' => 'Half day',
                'price' => 95.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['4x4 vehicle', 'Expert naturalist', 'Park entry'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Experienced drivers and guides. Remain in vehicle at all times.',
            ],
            [
                'name' => 'Walking Safari in Bardia',
                'description' => 'Guided walking safari on foot to track tigers and other wildlife. Thrilling and educational.',
                'type' => 'safari',
                'location' => 'Bardia National Park',
                'city' => 'Bardiya',
                'duration' => '3 hours',
                'price' => 75.00,
                'max_participants' => 6,
                'difficulty_level' => 'moderate',
                'includes' => ['Expert naturalist guide', 'Safety briefing', 'Tracking instruction'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Good fitness level required. Must follow guide instructions exactly.',
                'safety_info' => 'Highly trained guides. Small groups only. Emergency protocols in place.',
            ],
            [
                'name' => 'Crocodile Breeding Center Visit',
                'description' => 'Visit the crocodile breeding center in Chitwan to learn about conservation efforts.',
                'type' => 'wildlife',
                'location' => 'Chitwan National Park',
                'city' => 'Chitwan',
                'duration' => '1 hour',
                'price' => 15.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Entry fee', 'Guide', 'Educational talk'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Safe viewing areas. Educational environment.',
            ],
            [
                'name' => 'Ethnobotany Tour in the Himalayas',
                'description' => 'Learn about medicinal plants and traditional Himalayan healing practices.',
                'type' => 'educational',
                'location' => 'Annapurna Region',
                'city' => 'Kaski',
                'duration' => '1 day',
                'price' => 65.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Expert botanist guide', 'Plant identification book', 'Herbal tea tasting'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Interest in plants and nature. Walking involved.',
                'safety_info' => 'Knowledgeable guides. Do not touch unknown plants.',
            ],
            [
                'name' => 'Honey Hunting Experience',
                'description' => 'Witness traditional honey hunting from wild cliff bees. Ancient practice still alive today.',
                'type' => 'cultural',
                'location' => 'Gurung Villages',
                'city' => 'Kaski',
                'duration' => '1 day',
                'price' => 120.00,
                'max_participants' => 8,
                'difficulty_level' => 'moderate',
                'includes' => ['Transportation', 'Local guide', 'Honey tasting', 'Lunch with local family'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Some hiking required. Seasonal activity (spring/autumn).',
                'safety_info' => 'Experienced local honey hunters. View from safe distance.',
            ],
            [
                'name' => 'Skiing at Kalinchowk',
                'description' => 'Nepals only ski destination with basic ski slopes and equipment rental.',
                'type' => 'skiing',
                'location' => 'Kalinchowk',
                'city' => 'Dolakha',
                'duration' => '1 day',
                'price' => 85.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Ski equipment rental', 'Basic instruction', 'Lift access'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Winter months only (Dec-Feb). Basic fitness required.',
                'safety_info' => 'Basic slopes suitable for beginners. Safety equipment required.',
            ],
            [
                'name' => 'Snowboarding in Kalinchowk',
                'description' => 'Try snowboarding on Nepals only snow-covered slopes. Basic runs for beginners.',
                'type' => 'skiing',
                'location' => 'Kalinchowk',
                'city' => 'Dolakha',
                'duration' => '1 day',
                'price' => 95.00,
                'max_participants' => 10,
                'difficulty_level' => 'moderate',
                'includes' => ['Snowboard rental', 'Basic instruction', 'Lift access'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Winter months only. Some board sports experience helpful.',
                'safety_info' => 'Helmet required. Beginner slopes only.',
            ],
            [
                'name' => 'Tea Garden Tour in Ilam',
                'description' => 'Visit organic tea gardens in the beautiful hills of Ilam. Learn tea processing and tasting.',
                'type' => 'agricultural',
                'location' => 'Ilam Tea Gardens',
                'city' => 'Ilam',
                'duration' => '1 day',
                'price' => 45.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Garden tour', 'Tea processing demo', 'Tea tasting', 'Lunch', 'Souvenir tea'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Peaceful environment. Easy walking.',
            ],
            [
                'name' => 'Coffee Plantation Tour in Gulmi',
                'description' => 'Explore organic coffee farms in the mid-western hills. Learn roasting and brewing.',
                'type' => 'agricultural',
                'location' => 'Gulmi Coffee Farms',
                'city' => 'Gulmi',
                'duration' => 'Half day',
                'price' => 35.00,
                'max_participants' => 12,
                'difficulty_level' => 'easy',
                'includes' => ['Farm tour', 'Roasting demo', 'Coffee tasting', 'Bag of coffee'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Safe farm environment.',
            ],
            [
                'name' => 'Handicraft Shopping Tour',
                'description' => 'Guided tour to the best handicraft shops in Kathmandu. Support local artisans.',
                'type' => 'shopping',
                'location' => 'Thamel and Patan',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 40.00,
                'max_participants' => 8,
                'difficulty_level' => 'easy',
                'includes' => ['Shopping guide', 'Negotiation assistance', 'Quality guarantee'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Bring cash for purchases. Interest in handicrafts.',
                'safety_info' => 'Safe shopping areas. Trusted shops only.',
            ],
            [
                'name' => 'Pashmina Shopping Experience',
                'description' => 'Learn about genuine pashmina and shop for authentic cashmere products.',
                'type' => 'shopping',
                'location' => 'Pashmina Workshops',
                'city' => 'Kathmandu',
                'duration' => '2 hours',
                'price' => 25.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['Educational session', 'Quality authentication', 'Shopping assistance'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Interest in textiles.',
                'safety_info' => 'Trusted authentic dealers.',
            ],
            [
                'name' => 'Nightlife Tour in Thamel',
                'description' => 'Experience Kathmandus famous nightlife. Live music, bars, and restaurants.',
                'type' => 'nightlife',
                'location' => 'Thamel',
                'city' => 'Kathmandu',
                'duration' => 'Evening',
                'price' => 35.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Local guide', 'Bar recommendations', 'Cover charges', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Must be 21+. ID required.',
                'safety_info' => 'Local guide ensures safety. Safe areas only.',
            ],
            [
                'name' => 'Sunset Boat Ride on Phewa Lake',
                'description' => 'Peaceful boat ride on Pokharas beautiful lake during golden hour.',
                'type' => 'leisure',
                'location' => 'Phewa Lake',
                'city' => 'Pokhara',
                'duration' => '1 hour',
                'price' => 20.00,
                'max_participants' => 4,
                'difficulty_level' => 'easy',
                'includes' => ['Boat rental', 'Boatman', 'Peaceful sunset experience'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Life jackets provided. Experienced boatmen.',
            ],
            [
                'name' => 'Davis Falls and Caves Tour',
                'description' => 'Visit Pokharas famous underground waterfall and nearby caves.',
                'type' => 'sightseeing',
                'location' => 'Davis Falls',
                'city' => 'Pokhara',
                'duration' => 'Half day',
                'price' => 30.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Entry fees', 'Guide', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Some stairs at caves.',
                'safety_info' => 'Safe viewing areas. Guide supervision.',
            ],
            [
                'name' => 'World Peace Pagoda Hike',
                'description' => 'Short hike to the beautiful white stupa overlooking Pokhara and the Annapurna range.',
                'type' => 'hiking',
                'location' => 'World Peace Pagoda',
                'city' => 'Pokhara',
                'duration' => '3 hours',
                'price' => 35.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Boat crossing', 'Entry fee'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness. Uphill hiking.',
                'safety_info' => 'Safe trail. Experienced guide.',
            ],
            [
                'name' => 'Ghorepani Poon Hill Sunrise Trek',
                'description' => 'Short trek to the famous Poon Hill viewpoint for spectacular sunrise over the Annapurnas.',
                'type' => 'trekking',
                'location' => 'Poon Hill',
                'city' => 'Kaski',
                'duration' => '3-4 days',
                'price' => 450.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Porters', 'All meals', 'Accommodation', 'Permits', 'Transportation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Moderate fitness. Suitable for beginners.',
                'safety_info' => 'Popular safe trail. Experienced guides.',
            ],
            [
                'name' => 'Sarangkot Sunrise View Tour',
                'description' => 'Early morning drive to Sarangkot for breathtaking sunrise over the Annapurna range and Pokhara valley.',
                'type' => 'sightseeing',
                'location' => 'Sarangkot',
                'city' => 'Pokhara',
                'duration' => 'Half day',
                'price' => 35.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Breakfast', 'Guide'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Early morning departure. Suitable for all.',
                'safety_info' => 'Safe viewpoint. Experienced driver.',
            ],
            [
                'name' => 'Seti Gorge River Walking',
                'description' => 'Walk through the underground gorge carved by the Seti River. Unique geological experience.',
                'type' => 'adventure',
                'location' => 'Seti River Gorge',
                'city' => 'Pokhara',
                'duration' => '2 hours',
                'price' => 25.00,
                'max_participants' => 12,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Safety equipment', 'Entry fees'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Good balance required. Not for those with fear of heights.',
                'safety_info' => 'Safety harnesses provided. Trained guides.',
            ],
            [
                'name' => 'Bandipur Heritage Walk',
                'description' => 'Walking tour of the preserved hilltop Newari town of Bandipur. Architecture and mountain views.',
                'type' => 'cultural',
                'location' => 'Bandipur',
                'city' => 'Tanahun',
                'duration' => 'Half day',
                'price' => 40.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Local guide', 'Heritage entry fees', 'Tea break'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Walking on cobblestones.',
                'safety_info' => 'Safe heritage area. Knowledgeable local guide.',
            ],
            [
                'name' => 'Gorkha Palace and Temple Tour',
                'description' => 'Visit the historic palace of the Shah kings who unified Nepal. Ancient fort and temple complex.',
                'type' => 'cultural',
                'location' => 'Gorkha Durbar',
                'city' => 'Gorkha',
                'duration' => '1 day',
                'price' => 65.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Transportation', 'Guide', 'Entry fees', 'Lunch'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Many stairs to climb. Good fitness needed.',
                'safety_info' => 'Historic site. Care on stairs.',
            ],
            [
                'name' => 'Nuwakot Fortress Exploration',
                'description' => 'Explore the historic fortress that once guarded the Kathmandu Valley trade route.',
                'type' => 'cultural',
                'location' => 'Nuwakot Durbar',
                'city' => 'Nuwakot',
                'duration' => '1 day',
                'price' => 75.00,
                'max_participants' => 12,
                'difficulty_level' => 'moderate',
                'includes' => ['Transportation', 'Guide', 'Entry fees', 'Lunch'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Stairs and hills involved. Moderate fitness.',
                'safety_info' => 'Historic building. Care on steep stairs.',
            ],
            [
                'name' => 'Tansen Historical Tour',
                'description' => 'Explore the historic hill town of Tansen with its traditional Palpa architecture.',
                'type' => 'cultural',
                'location' => 'Tansen',
                'city' => 'Palpa',
                'duration' => '1 day',
                'price' => 55.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Local guide', 'Heritage sites entry'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Walking on hills.',
                'safety_info' => 'Safe hill town. Knowledgeable guide.',
            ],
            [
                'name' => 'Ilam Tea and Sightseeing Tour',
                'description' => 'Full day tour of Ilam including tea gardens, viewpoints, and local attractions.',
                'type' => 'sightseeing',
                'location' => 'Ilam',
                'city' => 'Ilam',
                'duration' => '1 day',
                'price' => 60.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Guide', 'Tea garden visit', 'Lunch'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Safe environment. Experienced driver.',
            ],
            [
                'name' => 'Antu Danda Sunrise Experience',
                'description' => 'Spectacular sunrise viewing from Antu Danda with mountain views and tea gardens.',
                'type' => 'sightseeing',
                'location' => 'Antu Danda',
                'city' => 'Ilam',
                'duration' => 'Half day',
                'price' => 45.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Breakfast', 'Guide'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Early morning start. Suitable for all.',
                'safety_info' => 'Safe viewpoint. Experienced guide.',
            ],
            [
                'name' => 'Kakani Strawberry Picking',
                'description' => 'Seasonal strawberry picking in the hills near Kathmandu with mountain views.',
                'type' => 'agricultural',
                'location' => 'Kakani',
                'city' => 'Nuwakot',
                'duration' => 'Half day',
                'price' => 30.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Strawberry picking', 'Lunch', 'Basket of strawberries'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Seasonal (Dec-April). Suitable for families.',
                'safety_info' => 'Safe farm environment.',
            ],
            [
                'name' => 'Shivapuri National Park Hike',
                'description' => 'Day hike in Kathmandus closest national park. Waterfall, Nagi Gompa, and forest trails.',
                'type' => 'hiking',
                'location' => 'Shivapuri National Park',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 55.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Park entry', 'Lunch', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness required. Uphill hiking.',
                'safety_info' => 'Marked trails. Experienced guide.',
            ],
            [
                'name' => 'Nagarjun Forest Hiking',
                'description' => 'Hike through the forest reserve to the Jamacho viewpoint with Kathmandu valley views.',
                'type' => 'hiking',
                'location' => 'Nagarjun Forest',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 40.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Park entry', 'Refreshments'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness. Uphill trail.',
                'safety_info' => 'Safe forest trail. Experienced guide.',
            ],
            [
                'name' => 'Champadevi Hill Hiking',
                'description' => 'Hike to the third highest hill around Kathmandu with panoramic valley and mountain views.',
                'type' => 'hiking',
                'location' => 'Champadevi',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 35.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Refreshments', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Moderate fitness. Steep uphill.',
                'safety_info' => 'Safe trail. Experienced guide.',
            ],
            [
                'name' => 'Phulchoki Hill Trek',
                'description' => 'Hike to the highest hill around Kathmandu. Famous for rhododendron forests and bird watching.',
                'type' => 'hiking',
                'location' => 'Phulchoki',
                'city' => 'Lalitpur',
                'duration' => '1 day',
                'price' => 50.00,
                'max_participants' => 15,
                'difficulty_level' => 'moderate',
                'includes' => ['Guide', 'Lunch', 'Transportation'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Good fitness. Full day hiking.',
                'safety_info' => 'Safe forest trail. Experienced birding guide available.',
            ],
            [
                'name' => 'Chitlang Organic Village Tour',
                'description' => 'Visit the organic village of Chitlang. Cheese production, orchards, and rural life.',
                'type' => 'cultural',
                'location' => 'Chitlang',
                'city' => 'Makwanpur',
                'duration' => '1 day',
                'price' => 60.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Transportation', 'Guide', 'Organic lunch', 'Cheese tasting'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Safe village environment.',
            ],
            [
                'name' => 'Namobuddha Monastery Stay',
                'description' => 'Overnight stay at the sacred Buddhist monastery of Namobuddha. Meditation and peace.',
                'type' => 'pilgrimage',
                'location' => 'Namobuddha',
                'city' => 'Kavrepalanchowk',
                'duration' => '1-2 days',
                'price' => 75.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Monastery stay', 'Vegetarian meals', 'Meditation session', 'Teaching'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Respectful behavior. Silent periods observed.',
                'safety_info' => 'Peaceful monastery. Monks provide guidance.',
            ],
            [
                'name' => 'Panauti Homestay Experience',
                'description' => 'Live with a traditional Newari family in the ancient town of Panauti. Authentic cultural immersion.',
                'type' => 'cultural',
                'location' => 'Panauti',
                'city' => 'Kavrepalanchowk',
                'duration' => '1-2 days',
                'price' => 55.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['Homestay accommodation', 'All meals', 'Cultural activities', 'Local guide'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Open to cultural exchange. Basic facilities.',
                'safety_info' => 'Safe family environment. Authentic experience.',
            ],
            [
                'name' => 'Bungamati and Khokana Tour',
                'description' => 'Visit traditional Newari villages known for wood carving and mustard oil production.',
                'type' => 'cultural',
                'location' => 'Bungamati and Khokana',
                'city' => 'Lalitpur',
                'duration' => 'Half day',
                'price' => 45.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Transportation', 'Craft demonstrations', 'Refreshments'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages.',
                'safety_info' => 'Safe village environment.',
            ],
            [
                'name' => 'Kirtipur Historical Walk',
                'description' => 'Walking tour of historic Kirtipur with its ancient temples and resistance history.',
                'type' => 'cultural',
                'location' => 'Kirtipur',
                'city' => 'Kathmandu',
                'duration' => 'Half day',
                'price' => 30.00,
                'max_participants' => 15,
                'difficulty_level' => 'easy',
                'includes' => ['Local guide', 'Temple entries', 'Newari snack'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Suitable for all ages. Hills and stairs.',
                'safety_info' => 'Safe area. Knowledgeable local guide.',
            ],
            [
                'name' => 'Dashain Festival Experience',
                'description' => 'Experience Nepals biggest festival with a local family. Tika blessings and celebrations.',
                'type' => 'festival',
                'location' => 'Kathmandu Valley',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 85.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['Family visit', 'Festival meal', 'Blessing ceremony', 'Gift'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Festival season only (Sept-Oct). Respectful behavior.',
                'safety_info' => 'Hosted by vetted families. Safe environment.',
            ],
            [
                'name' => 'Tihar Festival of Lights',
                'description' => 'Experience the festival of lights with a Nepali family. Lamps, rangoli, and celebrations.',
                'type' => 'festival',
                'location' => 'Kathmandu Valley',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 75.00,
                'max_participants' => 6,
                'difficulty_level' => 'easy',
                'includes' => ['Family visit', 'Festival dinner', 'Cultural activities', 'Gift'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Festival season only (Oct-Nov). Respectful behavior.',
                'safety_info' => 'Hosted by vetted families. Safe environment.',
            ],
            [
                'name' => 'Holi Festival Celebration',
                'description' => 'Join the colorful celebration of Holi in Kathmandu. Music, dancing, and colored powders.',
                'type' => 'festival',
                'location' => 'Kathmandu',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 40.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Colored powders', 'Protective gear', 'Lunch'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Festival day only (March). Bring old clothes.',
                'safety_info' => 'Guided to safe areas. Group safety.',
            ],
            [
                'name' => 'Teej Festival Experience',
                'description' => 'Witness the women festival dedicated to Parvati. Dancing, fasting, and red sarees.',
                'type' => 'festival',
                'location' => 'Pashupatinath',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 50.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Observation points', 'Cultural explanation', 'Refreshments'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Festival day only (August). Respectful observation.',
                'safety_info' => 'Large crowds expected. Stay with guide.',
            ],
            [
                'name' => 'New Year (Bisket Jatra) in Bhaktapur',
                'description' => 'Experience the wild chariot festival celebrating the Nepali New Year in Bhaktapur.',
                'type' => 'festival',
                'location' => 'Bhaktapur',
                'city' => 'Bhaktapur',
                'duration' => '1 day',
                'price' => 60.00,
                'max_participants' => 12,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Safe viewing points', 'Festival food', 'Safety briefing'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Mid-April only. Large crowds and excitement.',
                'safety_info' => 'Guide ensures safety. Viewing from safe zones.',
            ],
            [
                'name' => 'Indra Jatra Festival Tour',
                'description' => 'Witness the Kumari goddess being paraded through Kathmandu. Masked dances and celebrations.',
                'type' => 'festival',
                'location' => 'Kathmandu Durbar Square',
                'city' => 'Kathmandu',
                'duration' => '1 day',
                'price' => 55.00,
                'max_participants' => 10,
                'difficulty_level' => 'easy',
                'includes' => ['Guide', 'Viewing points', 'Cultural explanation', 'Refreshments'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Festival period only (Sept).',
                'safety_info' => 'Large crowds. Stay with guide.',
            ],
            [
                'name' => 'Mountain Photography Workshop',
                'description' => 'Learn landscape photography from professionals in the stunning Annapurna region.',
                'type' => 'workshop',
                'location' => 'Pokhara and Sarangkot',
                'city' => 'Pokhara',
                'duration' => '2 days',
                'price' => 350.00,
                'max_participants' => 8,
                'difficulty_level' => 'easy',
                'includes' => ['Professional photographer guide', 'Editing sessions', 'Transportation', 'Meals'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Bring your own camera. All skill levels welcome.',
                'safety_info' => 'Experienced guide. Safe locations.',
            ],
            [
                'name' => 'Astrology and Palm Reading Session',
                'description' => 'Traditional Nepali astrology consultation and palm reading by experienced practitioners.',
                'type' => 'wellness',
                'location' => 'Traditional Astrologer',
                'city' => 'Kathmandu',
                'duration' => '1 hour',
                'price' => 40.00,
                'max_participants' => 4,
                'difficulty_level' => 'easy',
                'includes' => ['Birth chart reading', 'Palm reading', 'Written predictions'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Birth details required. Open mind.',
                'safety_info' => 'Reputable practitioners. Entertainment purpose.',
            ],
            [
                'name' => 'Meditation Retreat at Kopan',
                'description' => 'Buddhist meditation retreat at the famous Kopan Monastery above Kathmandu.',
                'type' => 'wellness',
                'location' => 'Kopan Monastery',
                'city' => 'Kathmandu',
                'duration' => '3 days',
                'price' => 280.00,
                'max_participants' => 20,
                'difficulty_level' => 'easy',
                'includes' => ['Teachings', 'Meditation sessions', 'Vegetarian meals', 'Accommodation'],
                'is_featured' => true,
                'status' => 'active',
                'requirements' => 'Commitment to silence and schedule.',
                'safety_info' => 'Established monastery. Safe environment.',
            ],
            [
                'name' => 'Traditional Massage and Healing',
                'description' => 'Traditional Nepali massage and healing therapies from experienced practitioners.',
                'type' => 'wellness',
                'location' => 'Traditional Healing Center',
                'city' => 'Kathmandu',
                'duration' => '1.5 hours',
                'price' => 45.00,
                'max_participants' => 4,
                'difficulty_level' => 'easy',
                'includes' => ['Full body massage', 'Herbal oils', 'Steam bath'],
                'is_featured' => false,
                'status' => 'active',
                'requirements' => 'Inform of any medical conditions.',
                'safety_info' => 'Trained therapists. Clean environment.',
            ],
        ];

        foreach ($activities as $activityData) {
            $activityData['slug'] = Str::slug($activityData['name']) . '-' . uniqid();
            $activityData['rating'] = rand(38, 50) / 10;
            $activityData['google_rating'] = rand(42, 49) / 10;
            $activityData['google_review_count'] = rand(50, 1500);
            $activityData['tripadvisor_rating'] = rand(40, 50) / 10;
            $activityData['tripadvisor_review_count'] = rand(30, 1000);

            Activity::create($activityData);
        }
    }
}
